import type { IncomingMessage, ServerResponse } from "http";

// The production build already bundles the Express server into this CommonJS
// artifact. Importing the TypeScript source directly leaves an extensionless
// ESM import in Vercel's function output (`../server/index`), which Node cannot
// resolve at runtime.
// @ts-ignore -- dist/index.cjs is generated by `npm run build` before Vercel packages this function.
import serverBundle from "../dist/index.cjs";

type ServerBundle = {
  app: (request: IncomingMessage, response: ServerResponse) => unknown;
  appReady: Promise<unknown>;
};

const { app, appReady } = serverBundle as ServerBundle;

export default async function handler(
  request: IncomingMessage,
  response: ServerResponse,
) {
  await appReady;
  return app(request, response);
}
